INSERT INTO USER_DETAILS(ID, BIRTH_DATE, NAME)
VALUES(101, '1995-02-02', 'Jack');
INSERT INTO USER_DETAILS(ID, BIRTH_DATE, NAME)
VALUES(102, '1983-02-02', 'Tom');
INSERT INTO USER_DETAILS(ID, BIRTH_DATE, NAME)
VALUES(103, '1998-02-02', 'John');

INSERT INTO POSTS(USER_ID, DESCRIPTION) VALUES (101, 'I love java');
INSERT INTO POSTS(USER_ID, DESCRIPTION) VALUES (101, 'and python');
INSERT INTO POSTS(USER_ID, DESCRIPTION) VALUES (102, 'I love c#');
INSERT INTO POSTS(USER_ID, DESCRIPTION) VALUES (103, 'i like ruby');

